# Exported from:        http://xl-release-nightly.xebialabs.com:5516/
# Release version:      23.4.0-1019.113
# Date created:         Tue Oct 24 15:43:28 CEST 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
